exclude: [
  "include/emthrm/geometry/integral_geometry.hpp",
  "include/emthrm/graph/flow/maximum_flow/maximum_flow.hpp",
  "include/emthrm/graph_cost-free",
  "include/emthrm/math/fast_divisor.hpp",
  "test/graph_cost-free",
  "test/math/fast_divisor.hpp"
]
