description: C++ Library for Competitive Programming
exclude:
- include/emthrm/geometry/integral_geometry.hpp
- include/emthrm/graph_cost-free
- include/emthrm/math/fast_divisor.hpp
- test/graph_cost-free
- test/math/fast_divisor.hpp
plugins:
- jemoji
- jekyll-redirect-from
theme: jekyll-theme-minimal
title: cp-library
