name: cpplint

on: push

jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install cpplint

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v16
        with:
          files: |
            **/*.cpp
            **/*.hpp

      - name: Run tests
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            case "$file" in
              "include/emthrm/data_structure/binary_trie.hpp" | "include/emthrm/math/convolution/lcm_convolution.hpp" | "include/emthrm/string/aho-corasick.hpp" )
                cpplint --filter=-build/include_what_you_use,-legal/copyright,-runtime/int $file ;;
              "include/emthrm/math/bigint.hpp" | "include/emthrm/math/modint.hpp" | "include/emthrm/math/rational.hpp" )
                cpplint --filter=-legal/copyright,-runtime/explicit,-runtime/int,-whitespace/blank_line $file ;;
              "include/emthrm/util/template.hpp" )
                ;;  # skip
              "include/emthrm/util/timer.hpp" )
                cpplint --filter=-build/c++11,-legal/copyright,-runtime/int $file ;;
              "include/emthrm/util/xorshift.hpp" )
                cpplint --filter=-legal/copyright,-runtime/int,-runtime/threadsafe_fn $file ;;
              "include/emthrm/geometry/geometry.hpp" | *.test.cpp )
                cpplint --filter=-legal/copyright,-runtime/int,-whitespace/line_length $file ;;
              * )
                cpplint --filter=-legal/copyright,-runtime/int $file ;;
            esac
          done
