name: verify

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip3 install -U git+https://github.com/emthrm/verification-helper.git@develop

      - name: Run tests
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        run: oj-verify all --timeout 3600
