name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        run: oj-verify all --timeout 3600
